version: 2
updates:
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: daily
      open-pull-requests-limit: 2
      groups:
        npm-patch:
          patterns:
          - "*"
          update-types:
          - "patch"
        storybook:
          patterns:
            - "storybook"
            - "@storybook/*"
        vueuse:
          patterns:
            - "@vueuse/*"
        autocomplete:
          patterns:
            - "@algolia/*"
